### ISSUE TITLE
No Sensors found - better would be - No new sensors found - improvement

### ISSUE THREAD

**Issue by DG12** [ruuvi/station.localization#107]
2446
    "ident_ios": "",
      "ident_android": "add_tag_not_found",
      "ident_webui": "",
      "en": "No sensors found",

No **new**  sensors found .
Would be better
or 
**All detectable sensors are already known..**

I would put it in but I don't know all the other languages .

6014 
No sensors in Bluetooth range

also line 609
 "ident_ios": "DiscoverTable.NoDevicesSection.NotFound.text",
      "ident_android": "",
      "ident_webui": "",
      "en": "(No sensors in Bluetooth range)",

Then of course there is the best choice:
_"All your base are belong to us"_

**Comment by markoaamunkajo** [comment]
Considered, no changes made
