### ISSUE TITLE
All links going to ruuvi.com should use UTM

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/station.localization#108]
Description:

Android and iOS sources are separated with UTM url's. for example

Readme
Menu
Buy buttons
Language versions

iOS UTM tag to the link: ?utm_campaign=app_ua&utm_medium=referral&utm_source=ios
Android UTM tag to the link: ?utm_campaign=app_ua&utm_medium=referral&utm_source=android

Check together with @priyonto

**Comment by priyonto** [comment]
I have added separate item for iOS.

**Comment by markoaamunkajo** [comment]
I'm ignoring links under About/Help, assuming they are not in the scope, otherwise looking good.
QA passed
