### ISSUE TITLE
Finnish capitalisation issues

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/station.localization#63]
User feedback:

"Verkkoselaimessa näkyvien kuvaajien aika-akselin keston voi valita. Vaihtoehtoja ovat mm. “1 Tunti”, “1 Päivä” jne. Minusta olisi parempaa suomea kirjoittaa “1 tunti”, “1 päivä” jne. Samanlaista UI-viilausta voisi tehdä muuallakin. Isoja kirjaimia käytetään liian monessa paikassa."

https://f.ruuvi.com/t/isto-ja-pienet-kirjaimet/4954

**Comment by andreevdenis** [comment]
@io53 @markoaamunkajo

**Comment by markoaamunkajo** [comment]
Taking this card

**Comment by markoaamunkajo** [comment]
Created pull request let's see if it fixes all of them
